CREATE SCHEMA IF NOT EXISTS DB_PRUEBA;

USE DB_PRUEBA;

CREATE TABLE USERS
	(
	ID_USER INTEGER PRIMARY KEY AUTO_INCREMENT,
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	DNI VARCHAR(10),
	NAME VARCHAR(20),
	LASTNAME VARCHAR(20)
	);


INSERT INTO USERS (EMAIL, DNI, NAME, LASTNAME) VALUES
	('Audrey.Conley@empresa.com','AC-57939','Audrey','Conley'),
	('Sara.Wyatt@empresa.com','SW-68605','Sara','Wyatt'),
	('Tasha.Cross@empresa.com','TC-49609','Tasha','Cross'),
	('Martina.Howard@empresa.com','MH-94200','Martina','Howard'),
	('Latifah.Glover@empresa.com','LG-82330','Latifah','Glover'),
	('Quemby.Schroeder@empresa.com','QS-53622','Quemby','Schroeder'),
	('Renee.Franco@empresa.com','RF-21457','Renee','Franco'),
	('Heidi.Moss@empresa.com','HM-52145','Heidi','Moss'),
	('Dacey.Pennington@empresa.com','DP-48532','Dacey','Pennington'),
	('Alexa.Oneal@empresa.com','AO-91595','Alexa','Oneal'),
	('Tanya.Schroeder@empresa.com','TS-81946','Tanya','Schroeder'),
	('Alea.Hood@empresa.com','AH-87408','Alea','Hood'),
	('Leandra.Strickland@empresa.com','LS-21053','Leandra','Strickland'),
	('Gisela.Johns@empresa.com','GJ-41390','Gisela','Johns'),
	('Quin.Kidd@empresa.com','QK-11265','Quin','Kidd'),
	('Bianca.Sanchez@empresa.com','BS-49484','Bianca','Sanchez'),
	('Lacota.Gill@empresa.com','LG-84937','Lacota','Gill'),
	('Lilah.Rosario@empresa.com','LR-40230','Lilah','Rosario'),
	('Madeline.Rush@empresa.com','MR-14302','Madeline','Rush'),
	('Ariana.Wyatt@empresa.com','AW-73872','Ariana','Wyatt'),
	('Gloria.Mason@empresa.com','GM-54305','Gloria','Mason'),
	('Aileen.Bender@empresa.com','AB-87176','Aileen','Bender'),
	('Jaden.Walters@empresa.com','JW-30009','Jaden','Walters'),
	('Taylor.Dudley@empresa.com','TD-77233','Taylor','Dudley'),
	('Simone.Castaneda@empresa.com','SC-87166','Simone','Castaneda'),
	('Catherine.Floyd@empresa.com','CF-21000','Catherine','Floyd'),
	('Fallon.Pope@empresa.com','FP-16265','Fallon','Pope'),
	('Demetria.York@empresa.com','DY-89351','Demetria','York'),
	('Fleur.Bradshaw@empresa.com','FB-40084','Fleur','Bradshaw'),
	('Mara.Beach@empresa.com','MB-15644','Mara','Beach'),
	('Nomlanga.Hubbard@empresa.com','NH-56707','Nomlanga','Hubbard'),
	('Natalie.Perez@empresa.com','NP-53300','Natalie','Perez'),
	('Mari.Huff@empresa.com','MH-39441','Mari','Huff'),
	('Avye.Middleton@empresa.com','AM-15569','Avye','Middleton'),
	('Patricia.Blevins@empresa.com','PB-13450','Patricia','Blevins'),
	('Sandra.Fitzgerald@empresa.com','SF-72872','Sandra','Fitzgerald'),
	('Hadley.French@empresa.com','HF-77326','Hadley','French'),
	('Aurora.Macias@empresa.com','AM-36783','Aurora','Macias'),
	('Ramona.Downs@empresa.com','RD-69479','Ramona','Downs'),
	('Rosalyn.Hewitt@empresa.com','RH-22951','Rosalyn','Hewitt'),
	('Ruth.Molina@empresa.com','RM-52916','Ruth','Molina'),
	('Mallory.Gordon@empresa.com','MG-39982','Mallory','Gordon'),
	('Melanie.Allison@empresa.com','MA-86179','Melanie','Allison'),
	('Donna.Floyd@empresa.com','DF-96863','Donna','Floyd'),
	('Martha.Massey@empresa.com','MM-26010','Martha','Massey'),
	('Brianna.Sellers@empresa.com','BS-49640','Brianna','Sellers'),
	('Winifred.Norris@empresa.com','WN-48966','Winifred','Norris'),
	('Yoko.Chen@empresa.com','YC-46095','Yoko','Chen'),
	('Cara.Robinson@empresa.com','CR-88092','Cara','Robinson'),
	('Alfreda.Gilbert@empresa.com','AG-54447','Alfreda','Gilbert'),
	('Latifah.Estrada@empresa.com','LE-59059','Latifah','Estrada'),
	('Cassidy.Colon@empresa.com','CC-21180','Cassidy','Colon'),
	('Wanda.Rodriguez@empresa.com','WR-35066','Wanda','Rodriguez'),
	('Rana.Rogers@empresa.com','RR-60454','Rana','Rogers'),
	('Kelly.Garrett@empresa.com','KG-38751','Kelly','Garrett'),
	('Hayley.Parrish@empresa.com','HP-75691','Hayley','Parrish'),
	('Janna.Tanner@empresa.com','JT-37387','Janna','Tanner'),
	('Xyla.Barnes@empresa.com','XB-51841','Xyla','Barnes'),
	('Kessie.Ratliff@empresa.com','KR-60917','Kessie','Ratliff'),
	('Maggie.Herrera@empresa.com','MH-96116','Maggie','Herrera'),
	('Kyra.Perry@empresa.com','KP-98219','Kyra','Perry'),
	('Patience.Dillon@empresa.com','PD-99702','Patience','Dillon'),
	('Freya.Workman@empresa.com','FW-81330','Freya','Workman'),
	('Lacota.Curtis@empresa.com','LC-66712','Lacota','Curtis'),
	('Anastasia.Peterson@empresa.com','AP-78804','Anastasia','Peterson'),
	('Hayley.Bridges@empresa.com','HB-24443','Hayley','Bridges'),
	('Anika.Vazquez@empresa.com','AV-13491','Anika','Vazquez'),
	('Tamekah.Larsen@empresa.com','TL-96020','Tamekah','Larsen'),
	('Hedy.Barry@empresa.com','HB-98191','Hedy','Barry'),
	('Illana.Martinez@empresa.com','IM-51973','Illana','Martinez'),
	('Madeline.Morris@empresa.com','MM-15330','Madeline','Morris'),
	('Sacha.Anthony@empresa.com','SA-70663','Sacha','Anthony'),
	('Charde.Cox@empresa.com','CC-24609','Charde','Cox'),
	('McKenzie.Brewer@empresa.com','MB-96238','McKenzie','Brewer'),
	('Rhea.Barrera@empresa.com','RB-14213','Rhea','Barrera'),
	('Bertha.Martinez@empresa.com','BM-15702','Bertha','Martinez'),
	('Lana.Marsh@empresa.com','LM-50548','Lana','Marsh'),
	('Danielle.Gentry@empresa.com','DG-26864','Danielle','Gentry'),
	('Mara.Madden@empresa.com','MM-78248','Mara','Madden'),
	('Sybill.Reese@empresa.com','SR-67881','Sybill','Reese'),
	('Olympia.Sweet@empresa.com','OS-48807','Olympia','Sweet'),
	('Mariko.Christensen@empresa.com','MC-85374','Mariko','Christensen'),
	('Aretha.Mcdowell@empresa.com','AM-20627','Aretha','Mcdowell'),
	('Robin.Moss@empresa.com','RM-20978','Robin','Moss'),
	('Ila.Frederick@empresa.com','IF-80672','Ila','Frederick'),
	('Maya.Cross@empresa.com','MC-21207','Maya','Cross'),
	('Lisandra.Cobb@empresa.com','LC-70585','Lisandra','Cobb'),
	('Meghan.Jordan@empresa.com','MJ-11437','Meghan','Jordan'),
	('Anika.Burke@empresa.com','AB-83487','Anika','Burke'),
	('Remedios.Massey@empresa.com','RM-43453','Remedios','Massey'),
	('Maite.Pierce@empresa.com','MP-66975','Maite','Pierce'),
	('Gloria.Klein@empresa.com','GK-67551','Gloria','Klein'),
	('Kitra.Ramirez@empresa.com','KR-87809','Kitra','Ramirez'),
	('Maile.Moody@empresa.com','MM-92318','Maile','Moody'),
	('Regina.Gonzales@empresa.com','RG-13371','Regina','Gonzales'),
	('Rhea.White@empresa.com','RW-43869','Rhea','White'),
	('Leila.Dixon@empresa.com','LD-48186','Leila','Dixon'),
	('Clare.Estrada@empresa.com','CE-55146','Clare','Estrada'),
	('Nina.Whitehead@empresa.com','NW-58890','Nina','Whitehead'),
	('Idona.Hardin@empresa.com','IH-90108','Idona','Hardin');


